# Generated by Django 5.2.8 on 2025-11-29 21:55

import UTILS.db_utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CARDHOLDER_APP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(default=UTILS.db_utils.generate_id, editable=False, max_length=70, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('sandbox', 'sandbox'), ('production', 'production')], max_length=20)),
                ('card_id', models.CharField(max_length=50, unique=True)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('card_name', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='CARDHOLDER_APP.cardholder')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.CharField(default=UTILS.db_utils.generate_id, editable=False, max_length=70, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('sandbox', 'sandbox'), ('production', 'production')], max_length=20)),
                ('balance', models.IntegerField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_wallet', to='CARD_APP.card')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='CARDHOLDER_APP.cardholder')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=UTILS.db_utils.generate_id, editable=False, max_length=70, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('sandbox', 'sandbox'), ('production', 'production')], max_length=20)),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT'), ('REFUND', 'REFUND'), ('REVERSAL', 'REVERSAL')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(max_length=256)),
                ('old_balance', models.IntegerField()),
                ('new_balance', models.IntegerField()),
                ('meta_data', models.JSONField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_card', to='CARD_APP.card')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='CARD_APP.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
