# Generated by Django 5.2.8 on 2025-11-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARD_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_transaction_limit',
            field=models.IntegerField(choices=[(500000, 500000), (1000000, 1000000)], default=500000),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('MASTERCARD', 'MASTERCARD'), ('VISA', 'VISA')], default='MASTERCARD', max_length=20),
        ),
    ]
