# Generated by Django 5.2.8 on 2025-11-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARD_APP', '0002_card_card_transaction_limit_card_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('mastercard', 'mastercard'), ('visa', 'visa')], default='mastercard', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.CharField(max_length=255),
        ),
    ]
