# Generated by Django 5.2.8 on 2025-11-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARD_APP', '0003_alter_card_card_name_alter_card_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
