# Generated by Django 5.2.8 on 2025-11-30 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARD_APP', '0004_card_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_wallet', to='CARD_APP.card'),
        ),
    ]
