# Generated by Django 5.2.8 on 2025-11-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CARD_APP', '0005_alter_wallet_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='owner',
        ),
    ]
