# Generated by Django 5.2.8 on 2025-11-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARD_APP', '0006_remove_wallet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
