# Generated by Django 5.2.8 on 2025-11-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARD_APP', '0007_alter_transaction_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='deletion_reason',
            field=models.CharField(blank=True, null=True),
        ),
    ]
