# Generated by Django 5.2.8 on 2025-11-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationwallet',
            name='environment',
            field=models.CharField(choices=[('development', 'development'), ('sandbox', 'sandbox'), ('production', 'production')], default='sandbox', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organzationtransaction',
            name='environment',
            field=models.CharField(choices=[('development', 'development'), ('sandbox', 'sandbox'), ('production', 'production')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organzationtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT'), ('REFUND', 'REFUND'), ('REVERSAL', 'REVERSAL')], max_length=20),
        ),
    ]
