# Generated by Django 5.2.8 on 2025-11-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='key_id',
            field=models.CharField(default='<function now at 0xffff98149080>', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
