# Generated by Django 5.2.8 on 2025-11-29 02:29

import UTILS.db_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH_APP', '0003_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organization',
            managers=[
                ('objects', UTILS.db_utils.OrganizationManager()),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
