# Generated by Django 5.2.8 on 2025-11-28 22:31

import UTILS.db_utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AUTH_APP', '0002_apitoken_key_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardHolder',
            fields=[
                ('id', models.CharField(default=UTILS.db_utils.generate_id, editable=False, max_length=70, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('sandbox', 'sandbox'), ('production', 'production')], max_length=20)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('state_region', models.CharField(max_length=100)),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_flagged_for_fraud', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AUTH_APP.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
